### ISSUE TITLE
Question about random missing rates.

### ISSUE THREAD

**Issue by supercool706** [Haoyu-ha/LNLN#1]
Thank you for your contribution! In Table 9, do the results corresponding to each random missing rate represent the average of three random seeds(1111,1112,1113) or the best result from each run?

**Comment by Haoyu-ha** [comment]
The results in Table 9 represent the average performance from **three runs with different random seeds (1111, 1112, 1113)**. Thank you for your interest in our work.

**Comment by supercool706** [comment]
Thank you for answering my question！

**Comment by supercool706** [comment]
The data in Table 9 is the average value of the test results from three random seeds calculated manually, or is it derived from robust_evaluation.py?

**Comment by Haoyu-ha** [comment]
The results are obtained by the code calculation. Although the same result can be obtained by manual calculation, it is easy to make mistakes.

**Comment by supercool706** [comment]
Thank you for your patient answers.
