### ISSUE TITLE
关于data missing问题

### ISSUE THREAD

**Issue by xiyang2002** [Haoyu-ha/LNLN#3]
感谢你们团队的工作  我有个疑问 先做特征提取 再data missing 算信息泄露吗  提取的特征不是包含了很多帧的信息  你这样随机的missing 可能不能实现原始数据的不完整性

**Comment by Haoyu-ha** [comment]
你好，这个主要是与先前的一些工作保持了一样的设置，直接使用数据集提供的数据而没有自己提取。实际上，我认为特征提取并未提取时序信息，例如视频输入的特征是按帧提取的，文本输入的特征实际上是tokenizer分词后的vector,将其中的词mask为UNK后再使用BERT提取。

**Comment by xiyang2002** [comment]
感谢贵团队回答 ，table1，table2 是整体性能的鲁棒性比较   鲁棒性体现在什么地方 是所有missing rate 的结果平均吗

**Comment by Haoyu-ha** [comment]
是的，表示模型在不同程度干扰下的整体性能。Evaluation Settings and Criteria有说，另外我们在camera-ready版本中对一些细节进行了一些补充解释和修正，最近会放出来。

> 感谢贵团队回答 ，table1，table2 是整体性能的鲁棒性比较 鲁棒性体现在什么地方 是所有missing rate 的结果平均吗

**Comment by xiyang2002** [comment]
原始样本是一个3、4秒的视频吗

**Comment by Haoyu-ha** [comment]
> 原始样本是一个3、4秒的视频吗

有长有短，如果你有下数据集，其中RAW文件夹/压缩包就是视频原文件
