### ISSUE TITLE
关于effective_discriminator输入的疑问

### ISSUE THREAD

**Issue by 248780577** [Haoyu-ha/LNLN#5]
你好作者，首先感谢你们团队所做的工作，在拜读论文中，发现公式9与代码编写有所不同，这样写是用什么用意吗？期待您的解答。
![image](https://github.com/user-attachments/assets/c6f55aaa-517b-40d8-b3d3-ce25976ad64d)
lnln.py第164行
![image](https://github.com/user-attachments/assets/0147870c-4f09-49e8-8e4c-8cc163a24e79)

**Comment by Haoyu-ha** [comment]
你好，感谢你的提问。公式表示我们是希望生成的代理特征（H^1_p）分布与完整的语言模态特征的分布一致。而由于代理特征是主导模态特征的一部分，在实现中我们直接将H^1_p参与构成的H^1_d特征与完整的语言模态特征作为判别器的输入。直接使用h^1_p作为输入也是可行的，本质上是动机一样而实现方式稍有区别。

**Comment by 248780577** [comment]
感谢您的解答
