### ISSUE TITLE
关于各项指标值的选取

### ISSUE THREAD

**Issue by TouchYourYearn** [Haoyu-ha/LNLN#8]
作者团队你们好，感谢你们在多模态情感分析领域做出的贡献，你们的代码结构十分清晰易懂，让我深受启发。
这里有一个小的疑问，代码中的评估指标似乎是不同checkpoints中的最佳值，正如你们所说：分类指标好的未必在回归指标中表现良好，为了全面评估性能，对于每个指标的值，你们选择的是表现最好的那个checkpoint。但是这种评估方式会不会受到训练过程中的扰动性的影响？在噪声率为0.1的情况下，我输出了每一个epoch下的实验结果，发现在训练后期模型的整体性能（同一个epoch下的指标）相比论文有所下降，尽管current best 的输出结果的确与论文结果相近。那么在评估时，应该按照哪种方式选取？谢谢。

**Comment by TouchYourYearn** [comment]
补充：刚刚我没有完全理解您的意图，现在我纠正一下问题。我发现训练完一个epoch后，获取到了六个指标的pth文件，那么在评估模型鲁棒性的时候，我需要分别加载这六个权重文件到robust_evaluation.py,然后运行六次，得到一个整体的结果是吗？

**Comment by Haoyu-ha** [comment]
> 补充：刚刚我没有完全理解您的意图，现在我纠正一下问题。我发现训练完一个epoch后，获取到了六个指标的pth文件，那么在评估模型鲁棒性的时候，我需要分别加载这六个权重文件到robust_evaluation.py,然后运行六次，得到一个整体的结果是吗？

是的，你理解没错，论文中LNLN以及其他Baseline方法也是按此方法计算出结果并进行对比。如果您想根据某一个指标选取参数并测试鲁棒性，我认为只要是公平且合理的对比都可以。
