### ISSUE TITLE
训练结果

### ISSUE THREAD

**Issue by luluyis** [Haoyu-ha/LNLN#9]
①你好，我们进行了代码复现，结果无法达到论文展示结果。
②先进模型对比中，您的上一篇论文ALMT论文训练结果与本篇论文展示ALMT结果有较大差距，请问您是对先进模型训练时都进行了文本模态的缺失操作吗

**Comment by Haoyu-ha** [comment]
你好。关于问题1，data missing本身会增大训练中的随机性，可能会导致不同的机器有差异。我这边收到的反馈是有的人能复现有的人也报告差一点。我这边回头也换check一下。关于问题2，baseline方法训练时也有data missing。关于ALMT，你可以看一下已经close的issue里头的一个回答，有人问过一样的问题。

**Comment by luluyis** [comment]
好的感谢您的解答

**Comment by luluyis** [comment]
麻烦再询问您一下，别的模型的对比结果是你们单独再运行他们的模型出来的结果吗？是在同样也存在datamissing的情况下运行的吗？

**Comment by Haoyu-ha** [comment]
> 麻烦再询问您一下，别的模型的对比结果是你们单独再运行他们的模型出来的结果吗？是在同样也存在datamissing的情况下运行的吗？

你好，是的。为了保证评估的一致性，别的模型的结果是重新跑的，找到较好的参数保存并在和LNLN相同的机器和环境下进行的测试。由于是相同机器和环境，因此这些方法在不同data missing rate测试时使用的数据也是一致的。

**Comment by luluyis** [comment]
感谢您的解答
